name: "Publish Website"
on:
  push:
    branches:
      - website
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      WEBSITE_DIR: ./website
      PLUGIN_DIR: ./website/plugins/gatsby-api-source/
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      AWS_RUNTIME_DIR: ./aws-runtime
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Use node version 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Set git author
        run: |
          git config --global user.email "markus.ecker@gmail.com"
          git config --global user.name "Markus Ecker"
      - name: Install dependencies
        run: |
          npm install gh-pages gatsby -g
      - name: Build .jsii
        run: yarn install && yarn build
        working-directory: ${{env.AWS_RUNTIME_DIR}}
      - name: Install packages
        run: npm install
        working-directory: ${{env.WEBSITE_DIR}}
      - name: Install plugin packages
        run: npm install
        working-directory: ${{env.PLUGIN_DIR}}
      - name: Build Website
        run: gatsby build
        working-directory: ${{env.WEBSITE_DIR}}
      - name: Publish to GitHub Pages
        run: gh-pages --dist public --branch main --repo https://${{ env.GH_TOKEN }}@github.com/cloudcamphq/cloudcamphq.github.io.git
        working-directory: ${{env.WEBSITE_DIR}}
